spring.application.name=todoist-mp-api

security.jwt.secret=${SECURITY_SECRET}
security.jwt.issuer=todoist_mp_api.aome.com
security.jwt.expiration=3600

spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.0.1.14:5432/todoist_mp_db

server.port=8080
