create table tasker(
                       id bigint primary key generated by default as identity,
                       todoist_username varchar(128) not null,
                       todoist_id bigint not null,
                       todoist_token varchar(128) not null unique,
                       telegram_token varchar(256) not null unique,
                       mp int not null default 0
);
