create table reward
(
    id        bigint primary key generated by default as identity,
    user_id   bigint      not null references tasker (id) on delete cascade,
    amount    int         not null default 0,
    content   text        not null,
    type      varchar(32) not null default 'REWARD',
    timestamp timestamptz          default now()
);
