create table mp_transaction
(
    id         bigint primary key generated by default as identity,
    tasker_id  bigint not null references tasker (id) on delete cascade,
    delta_mp   int not null default 0,
    timestamp  timestamptz  default now(),
    task_count int          default 0
);
