create table task
(
    id           bigint primary key generated by default as identity,
    tasker_id    bigint references tasker (id),
    content      text not null,
    description  text,
    completed_at timestamptz,
    mp           int default 0
);
