create table task
(
    id           bigint primary key generated by default as identity,
    tasker_id    bigint not null references tasker (id) on delete cascade,
    content      text not null,
    description  text,
    completed_at timestamptz,
    mp           int default 0
);
