-- Создание таблицы tasker
CREATE TABLE IF NOT EXISTS tasker (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    todoist_username VARCHAR(128) NOT NULL,
    todoist_id       BIGINT       NOT NULL UNIQUE,
    todoist_token    VARCHAR(128) NOT NULL UNIQUE,
    telegram_token   VARCHAR(256) NOT NULL UNIQUE,
    mp               INT          NOT NULL DEFAULT 0
);

-- Создание таблицы task
CREATE TABLE IF NOT EXISTS task (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tasker_id    BIGINT NOT NULL REFERENCES tasker (id) ON DELETE CASCADE,
    content      TEXT   NOT NULL,
    description  TEXT,
    completed_at TIMESTAMPTZ,
    mp           INT DEFAULT 0
);

-- Создание таблицы mp_transaction
CREATE TABLE IF NOT EXISTS mp_transaction (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tasker_id  BIGINT NOT NULL REFERENCES tasker (id) ON DELETE CASCADE,
    delta_mp   INT    NOT NULL DEFAULT 0,
    timestamp  TIMESTAMPTZ     DEFAULT NOW(),
    task_count INT             DEFAULT 0
);

-- Создание таблицы reward
CREATE TABLE IF NOT EXISTS reward (
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id   BIGINT      NOT NULL REFERENCES tasker (id) ON DELETE CASCADE,
    amount    INT         NOT NULL DEFAULT 0,
    content   TEXT        NOT NULL,
    type      VARCHAR(32) NOT NULL DEFAULT 'REWARD',
    timestamp TIMESTAMPTZ          DEFAULT NOW()
);

-- Создание индексов для улучшения производительности
CREATE INDEX IF NOT EXISTS idx_tasker_telegram_token ON tasker(telegram_token);
CREATE INDEX IF NOT EXISTS idx_tasker_todoist_token ON tasker(todoist_token);
CREATE INDEX IF NOT EXISTS idx_task_tasker_id ON task(tasker_id);
CREATE INDEX IF NOT EXISTS idx_mp_transaction_tasker_id ON mp_transaction(tasker_id);
CREATE INDEX IF NOT EXISTS idx_reward_user_id ON reward(user_id);
